[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # "alembic>=1.18.4",
    # "asyncpg>=0.31.0",
    "dotenv>=0.9.9",
    "fastapi>=0.129.0",
    # "psycopg[binary]>=3.3.2",
    # "sqlalchemy>=2.0.46",
    # "sqlmodel>=0.0.34",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.2",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlmodel>=0.0.34",
    "uvicorn[standard]>=0.40.0",
]
